name: Vercel Preview Deployment

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
    push:
        branches: 
            - develop
jobs:
    Deploy-Preview:
        runs-on: ubuntu-latest
        steps:

            - uses: actions/checkout@v3

            - name: Install Vercel CLI
              run: npm install --global vercel@latest
            
            - name: Debug Secrets
              run: |
                echo "VERCEL_TOKEN is set: ${{ secrets.VERCEL_TOKEN != '' }}"
                echo "VERCEL_ORG_ID is set: ${{ secrets.VERCEL_ORG_ID != '' }}"
                echo "VERCEL_PROJECT_ID is set: ${{ secrets.VERCEL_PROJECT_ID != '' }}"
          
            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=develop --token=${{ secrets.VERCEL_TOKEN }} --debug

            - name: Build Projsect Artifacts
              run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
              env:
                VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

            - name: Deploy Project Artifacts
              run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
              env:
                VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}